const http=require('http');
const fs=require('fs');
const path=require('path');
const url=require('url');
const crypto=require('crypto');
const zlib=require('zlib');

const PORT=Number(process.env.ERP_PORT||0);
const DATA_DIR=path.join(__dirname,'..','data');
const DATA_FILE=process.env.ERP_DB_FILE||path.join(DATA_DIR,'swaraj-erp.json');
const siteDb=require('./db');
const siteStore=require('./store');
let persistChain=Promise.resolve();
const SECRET=process.env.JWT_SECRET||'swaraj-erp-local-secret-change-me';
const ADMIN_EMAIL=(process.env.ERP_ADMIN_EMAIL||process.env.RESET_EMAIL||process.env.INITIAL_ADMIN_EMAIL||'admin@swaraj.local').toLowerCase();
const ADMIN_PASSWORD=process.env.ERP_ADMIN_PASSWORD||process.env.ADMIN_PASSWORD||process.env.INITIAL_ADMIN_PASSWORD||'Swaraj#123';
fs.mkdirSync(DATA_DIR,{recursive:true});

const companiesSeed=[
{id:'ds-swaraj',code:'DS',name:'DS Swaraj Agro',description:'Solar solutions & PM Surya Ghar',address:'Gokhana Bazar, NC College Road, Jajpur, Odisha - 755007',gstin:'21CIIPB9638R2ZP',pan:'CIIPB9638R',state:'Odisha',state_code:'21',pin:'755007',phone:'9337801437',email:'swarajagro@proton.me',bank_name:'HDFC Bank',bank_branch:'Jajpur Town',account_number:'50200114712024',ifsc:'HDFC0002310',account_type:'Current',logo:'/assets/logos/ds-swaraj-agro.png',terms:['Goods once sold will not be taken back or exchanged.','Payment is due as per the agreed credit period.','Interest at 18% p.a. may be charged on overdue balances.','Subject to Jajpur jurisdiction only.','E. & O.E.'],invoice_prefix:'INV',quotation_prefix:'QTN',proforma_prefix:'PI',purchase_prefix:'PUR',challan_prefix:'DC'},
{id:'swaraj',code:'SA',name:'Swaraj Agro',description:'Agricultural implements & spare parts',address:'Sahoo Complex, Gokhana Bazar, NC College Road, Jajpur, Odisha - 755007',gstin:'21CIIPB9638R1ZQ',pan:'CIIPB9638R',state:'Odisha',state_code:'21',pin:'755007',phone:'8763645106',email:'rajkishorebehera970@gmail.com',bank_name:'Bank of Baroda',bank_branch:'Bhabaniganj',account_number:'43400200000163',ifsc:'BARB0BHABAN',account_type:'Current',logo:'/assets/logos/swaraj-agro.png',terms:['Goods once sold will not be taken back or exchanged.','Payment is due as per the agreed credit period.','Interest at 18% p.a. may be charged on overdue balances.','Subject to Jajpur jurisdiction only.','E. & O.E.'],invoice_prefix:'INV',quotation_prefix:'QTN',proforma_prefix:'PI',purchase_prefix:'PUR',challan_prefix:'DC'},
{id:'md-agro',code:'MD',name:'MD Agro Traders',description:'Farm machinery manufacturer & distributor',address:'Gokhana Bazar, NC College Road, Jajpur, Odisha - 755007',gstin:'21DSRPB8823G1ZQ',pan:'DSRPB8823G',state:'Odisha',state_code:'21',pin:'755007',phone:'8260274509',email:'beherasantilata80@gmail.com',bank_name:'HDFC Bank',bank_branch:'Jajpur Town',account_number:'50200088404786',ifsc:'HDFC0002310',account_type:'Current',logo:'/assets/logos/md-agro-traders.png',terms:['Goods once sold will not be taken back or exchanged.','Payment is due as per the agreed credit period.','Interest at 18% p.a. may be charged on overdue balances.','Subject to Jajpur jurisdiction only.','E. & O.E.'],invoice_prefix:'INV',quotation_prefix:'QTN',proforma_prefix:'PI',purchase_prefix:'PUR',challan_prefix:'DC'}
];
const defaultPerms={viewAmounts:true,recordSales:true,recordPurchases:true,manageProducts:true,managePayments:true,manageSettings:true};
function uid(){return crypto.randomBytes(12).toString('hex')}
function now(){return new Date().toISOString()}
function money(n){return Math.round((Number(n)||0)*100)/100}
function safe(v,n=500){return String(v??'').trim().slice(0,n)}
function fy(date){const d=new Date(date||now());const y=d.getMonth()>=3?d.getFullYear():d.getFullYear()-1;return `${String(y).slice(-2)}-${String(y+1).slice(-2)}`}
function clone(v){return JSON.parse(JSON.stringify(v))}
function hashPassword(p,salt=crypto.randomBytes(16).toString('hex')){return `${salt}$${crypto.pbkdf2Sync(String(p),salt,100000,32,'sha256').toString('hex')}`}
function verifyPassword(p,h){try{const [salt,hex]=String(h).split('$');const out=crypto.pbkdf2Sync(String(p),salt,100000,32,'sha256').toString('hex');return crypto.timingSafeEqual(Buffer.from(out),Buffer.from(hex))}catch{return false}}
function signToken(userId,remember){const payload=JSON.stringify({sub:userId,exp:Date.now()+(remember?30*864e5:12*3600e3)});const b=Buffer.from(payload).toString('base64url');const sig=crypto.createHmac('sha256',SECRET).update(b).digest('base64url');return `${b}.${sig}`}
function readToken(t){try{const [b,s]=String(t||'').split('.');const good=crypto.createHmac('sha256',SECRET).update(b).digest('base64url');if(!crypto.timingSafeEqual(Buffer.from(s),Buffer.from(good)))return null;const p=JSON.parse(Buffer.from(b,'base64url').toString());return p.exp>Date.now()?p:null}catch{return null}}
function initial(){if(fs.existsSync(DATA_FILE))return JSON.parse(fs.readFileSync(DATA_FILE,'utf8'));const ts=now();const db={version:2,createdAt:ts,settings:{appName:'Swaraj ERP',currency:'INR',defaultGstRate:18,roundOff:true},companies:clone(companiesSeed),users:[{id:'admin',name:'Administrator',email:ADMIN_EMAIL,passwordHash:hashPassword(ADMIN_PASSWORD),role:'Administrator',isAdmin:true,permissions:clone(defaultPerms),createdAt:ts,updatedAt:ts}],parties:[],products:[],documents:[],payments:[],expenses:[],stockMovements:[],accounts:[],ledgerEntries:[],auditLogs:[],counters:{}};for(const c of db.companies){for(const [name,type] of [['Cash','Cash & Bank'],['Bank','Cash & Bank'],['Inventory','Asset'],['Sales','Income'],['Purchase','Expense'],['Expenses','Expense'],['Accounts Receivable','Receivable'],['Accounts Payable','Payable']])db.accounts.push({id:uid(),companyId:c.id,name,type,balance:0,createdAt:ts,updatedAt:ts})}save(db);return db}
function save(dbState){const tmp=DATA_FILE+'.tmp';fs.mkdirSync(DATA_DIR,{recursive:true});fs.writeFileSync(tmp,JSON.stringify(dbState,null,2));fs.renameSync(tmp,DATA_FILE);const snapshot=clone(dbState);persistChain=persistChain.then(async()=>{const mongo=await siteDb.getDb();if(mongo)await mongo.collection('erp').replaceOne({_id:'main'},{_id:'main',...snapshot},{upsert:true});}).catch(err=>console.error('[ERP] persistence error:',err.message));return persistChain}
let db=initial();

async function initializeERP(){
  const mongo=await siteDb.getDb();
  if(mongo){
    const doc=await mongo.collection('erp').findOne({_id:'main'});
    if(doc){const {_id,...rest}=doc;db=rest;}
    else await mongo.collection('erp').insertOne({_id:'main',...db});
  }
  await syncWebsiteProducts();
  return db;
}

function siteCompanyForProduct(p){return p.category==='Solar Solution'?'ds-swaraj':'swaraj'}
function parsePrice(v){const n=Number(String(v??'').replace(/[^0-9.\-]/g,''));return Number.isFinite(n)?n:0}
function formatPrice(v){const n=Number(v)||0;return n>0?'₹ '+Math.round(n).toLocaleString('en-IN'):'Contact for Price'}
async function syncWebsiteProducts(){
  const source=await siteStore.read();
  const sourceProducts=Array.isArray(source.products)?source.products:[];
  const siteProductIds=new Set(sourceProducts.map(p=>p.erpProductId||p.id));
  let erpChanged=false;
  for(const p of sourceProducts){
    const companyId=siteCompanyForProduct(p);
    const erpId=p.erpProductId||p.id;
    let ep=db.products.find(x=>x.id===erpId);
    if(!ep){
      ep={id:erpId,companyId,sku:p.sku||'',name:p.name,category:p.subcategory||p.category,hsn:p.hsn||'',unit:p.unit||'pcs',gstRate:Number(p.gstRate)||0,purchasePrice:Number(p.purchasePrice)||0,salePrice:parsePrice(p.salePrice??p.price),minStock:Number(p.minStock)||0,openingQty:Number(p.openingQty)||0,openingValue:Number(p.openingValue)||0,active:p.active!==false,createdAt:now(),updatedAt:now(),siteProductId:p.id,description:p.description||'',subcategory:p.subcategory||'',image:p.image||'',gallery:Array.isArray(p.gallery)?p.gallery.slice():[],featured:!!p.featured};
      db.products.push(ep);erpChanged=true;
    }else{
      const next={companyId,name:p.name,category:p.subcategory||p.category,description:p.description||'',subcategory:p.subcategory||'',salePrice:parsePrice(p.salePrice??p.price),active:p.active!==false,siteProductId:p.id,image:p.image||'',gallery:Array.isArray(p.gallery)?p.gallery.slice():[],featured:!!p.featured};
      let changed=false;
      for(const [k,v] of Object.entries(next)){if(ep[k]!==v){ep[k]=v;changed=true;}}
      if(changed){ep.updatedAt=now();erpChanged=true;}
    }
  }
  for(const ep of db.products){
    if((ep.companyId==='swaraj'||ep.companyId==='ds-swaraj') && ep.siteProductId && !siteProductIds.has(ep.id) && ep.active!==false){ep.active=false;ep.updatedAt=now();erpChanged=true;}
  }
  // Keep the website's product master aligned with ERP linkage fields without replacing the whole site document blindly.
  const needsSiteUpdate=sourceProducts.some(p=>p.erpProductId!==(p.erpProductId||p.id) || p.erpCompanyId!==siteCompanyForProduct(p));
  if(needsSiteUpdate){
    await siteStore.update(d=>{
      for(const p of d.products||[]){p.erpProductId=p.erpProductId||p.id;p.erpCompanyId=p.erpCompanyId||siteCompanyForProduct(p);}
    });
  }
  if(erpChanged) await save(db);
  return db;
}
async function syncERPProductToWebsite(ep){
  if(!ep || !['swaraj','ds-swaraj'].includes(ep.companyId)) return;
  await siteStore.update(d=>{
    d.products=Array.isArray(d.products)?d.products:[];
    const idx=d.products.findIndex(p=>p.erpProductId===ep.id || p.id===ep.siteProductId || p.id===ep.id);
    if(ep.active===false){ if(idx>=0)d.products.splice(idx,1); return; }
    const category=ep.companyId==='ds-swaraj'?'Solar Solution':'Farm Machinery';
    const patch={id:idx>=0?d.products[idx].id:(ep.siteProductId||ep.id),erpProductId:ep.id,erpCompanyId:ep.companyId,name:ep.name,category,subcategory:ep.subcategory||ep.category||'',price:formatPrice(ep.salePrice),description:ep.description||'',image:ep.image||'',gallery:Array.isArray(ep.gallery)?ep.gallery:[],featured:!!ep.featured};
    if(idx>=0)d.products[idx]=Object.assign(d.products[idx],patch); else d.products.push(patch);
  });
}
async function syncEnquiryToParty(enquiry){
  if(!enquiry || !enquiry.phone) return;
  const companyId=enquiry.category==='Solar Solution'?'ds-swaraj':'swaraj';
  const digits=String(enquiry.phone).replace(/\D/g,'');
  let party=db.parties.find(p=>p.companyId===companyId && p.type==='customer' && String(p.phone||'').replace(/\D/g,'')===digits);
  if(!party){party={id:uid(),companyId,type:'customer',name:safe(enquiry.name,180),phone:safe(enquiry.phone,50),email:'',address:safe(enquiry.location,400),gstin:'',state:'Odisha',stateCode:'21',pin:'',openingBalance:0,balanceType:'receivable',notes:safe(enquiry.message,300),createdAt:now(),updatedAt:now()};db.parties.push(party);}else{party.name=safe(enquiry.name,180);if(enquiry.location)party.address=safe(enquiry.location,400);if(enquiry.message)party.notes=safe(enquiry.message,300);party.updatedAt=now();}
  await save(db);
  return party;
}
function userPublic(u){return {id:u.id,name:u.name,email:u.email,role:u.role,isAdmin:!!u.isAdmin,permissions:u.permissions||{}}}
function auth(req,res,adminOnly=false){if(req.__siteAdmin){const u=db.users.find(x=>x.id==='admin')||db.users.find(x=>x.isAdmin);if(!u){json(res,401,{error:'ERP administrator is not initialized'});return null}req.user=u;return u}const q=url.parse(req.url,true).query;const h=req.headers.authorization||'';const token=h.startsWith('Bearer ')?h.slice(7):(q.token||'');const p=readToken(token);if(!p){json(res,401,{error:'Authentication required'});return null}const u=db.users.find(x=>x.id===p.sub);if(!u){json(res,401,{error:'User not found'});return null}if(adminOnly&&!u.isAdmin){json(res,403,{error:'Administrator access required'});return null}req.user=u;return u}
function json(res,status,data){const b=Buffer.from(JSON.stringify(data));res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Content-Length':b.length,'Cache-Control':'no-store'});res.end(b)}
function text(res,status,data,type='text/plain; charset=utf-8'){const b=Buffer.from(data);res.writeHead(status,{'Content-Type':type,'Content-Length':b.length,'Cache-Control':'no-store'});res.end(b)}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>s+=c);req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}})})}
function findCompany(id){return db.companies.find(c=>c.id===id)}
function findProduct(id){return db.products.find(p=>p.id===id)}
function stock(companyId,productId){const p=findProduct(productId);let n=Number(p?.openingQty||0);for(const m of db.stockMovements.filter(x=>x.companyId===companyId&&x.productId===productId)){n+=(m.type==='in'||m.type==='opening'||m.type==='return_in'?1:-1)*Number(m.qty||0)}return money(n)}
function products(companyId){return db.products.filter(p=>p.companyId===companyId&&p.active!==false).map(p=>({...clone(p),stock:stock(companyId,p.id),stock_value:money(stock(companyId,p.id)*(Number(p.purchasePrice)||0))}))}
function partyBalances(companyId){return db.parties.filter(p=>p.companyId===companyId).map(p=>{let doc=0;for(const d of db.documents){if(d.partyId!==p.id||d.status==='cancelled')continue;if(p.type==='customer'&&['invoice','non_gst'].includes(d.type))doc+=Number(d.total||0);if(p.type==='supplier'&&d.type==='purchase')doc+=Number(d.total||0)}const pay=db.payments.filter(x=>x.partyId===p.id&&x.type===(p.type==='customer'?'receipt':'payment')).reduce((s,x)=>s+Number(x.amount||0),0);return {...clone(p),outstanding:money(Number(p.openingBalance||0)+doc-pay)}})}
function nextNo(companyId,type,date){const c=findCompany(companyId);const prefix={invoice:(c.invoicePrefix||c.invoice_prefix||'INV'),non_gst:(c.invoicePrefix||c.invoice_prefix||'INV')+'-NG',quotation:(c.quotationPrefix||c.quotation_prefix||'QTN'),proforma:(c.proformaPrefix||c.proforma_prefix||'PI'),purchase:(c.purchasePrefix||c.purchase_prefix||'PUR'),delivery_challan:(c.challanPrefix||c.challan_prefix||'DC'),credit_note:'CN',debit_note:'DN'}[type]||'DOC';const key=`${companyId}|${type}|${fy(date)}`;db.counters[key]=(db.counters[key]||0)+1;return `${prefix}/${fy(date)}/${String(db.counters[key]).padStart(4,'0')}`}
function audit(req,action,entity,entityId,companyId,details){db.auditLogs.unshift({id:uid(),userId:req.user.id,companyId:companyId||null,action,entity,entityId:entityId||null,details:details||{},createdAt:now()});db.auditLogs=db.auditLogs.slice(0,1000)}
function calcDoc(b,items,c){let subtotal=0,discount=0,cgst=0,sgst=0,igst=0;const same=!b.placeOfSupply||safe(b.placeOfSupply).toLowerCase()===safe(c.state||'').toLowerCase()||safe(b.placeOfSupply)===safe(c.stateCode||c.state_code||'');const taxableItems=items.map(it=>{const qty=Number(it.qty)||0,price=Number(it.unitPrice)||0,disc=Number(it.discount)||0,base=money(Math.max(0,qty*price-disc)),rate=Number(it.gstRate)||0;subtotal+=money(qty*price);discount+=disc;let cg=0,sg=0,ig=0;if(b.type!=='non_gst'&&b.type!=='delivery_challan'&&b.type!=='quotation'&&b.type!=='proforma'){if(same){cg=money(base*rate/200);sg=cg}else ig=money(base*rate/100)}cgst+=cg;sgst+=sg;igst+=ig;return {...it,qty,unitPrice:price,discount:disc,taxable:base,cgst:cg,sgst:sg,igst:ig,lineTotal:money(base+cg+sg+ig)}});const taxable=money(subtotal-discount);const raw=money(taxable+cgst+sgst+igst);const total=b.round_off===false||b.round_off==='false'?raw:money(Math.round(raw));return {items:taxableItems,subtotal:money(subtotal),discount:money(discount),taxable,cgst:money(cgst),sgst:money(sgst),igst:money(igst),roundOff:money(total-raw),total}}
function insertDoc(req,b){const c=findCompany(b.companyId);if(!c)throw Error('Company not found');const items=(b.items||[]).filter(x=>x.product_id||x.productId||x.name).map(x=>({productId:x.product_id||x.productId,name:x.name,hsn:x.hsn,unit:x.unit,qty:Number(x.qty)||0,unitPrice:Number(x.unit_price??x.unitPrice)||0,discount:Number(x.discount)||0,gstRate:Number(x.gst_rate??x.gstRate)||0}));const calc=calcDoc(b,items,c);const d={id:uid(),companyId:b.companyId,partyId:b.partyId||null,type:b.type,number:b.number||nextNo(b.companyId,b.type,b.date),date:b.date||now().slice(0,10),status:b.status||'posted',placeOfSupply:safe(b.place_of_supply??b.placeOfSupply,80),refNo:safe(b.ref_no??b.refNo,100),ewayBillNo:safe(b.eway_bill_no??b.ewayBillNo,100),notes:safe(b.notes,800),subtotal:calc.subtotal,discount:calc.discount,taxable:calc.taxable,cgst:calc.cgst,sgst:calc.sgst,igst:calc.igst,roundOff:calc.roundOff,total:calc.total,paymentMode:safe(b.payment_mode??b.paymentMode,50),paymentStatus:(b.mark_paid?'paid':'unpaid'),dueDate:safe(b.due_date??b.dueDate,20),terms:b.terms||c.terms||[],metadata:b.metadata||{},createdBy:req.user.id,createdAt:now(),updatedAt:now(),items:[]};for(const it of calc.items){const p=findProduct(it.productId);d.items.push({...it,id:uid(),name:it.name||p?.name||'',hsn:it.hsn||p?.hsn||'',unit:it.unit||p?.unit||'pcs'})}
 if(['invoice','non_gst','purchase','credit_note','debit_note'].includes(d.type)){const sign=d.type==='purchase'||d.type==='credit_note'?'in':'out';for(const it of d.items){if(!it.productId)continue;if(sign==='out'&&stock(d.companyId,it.productId)<it.qty)throw Error(`Insufficient stock for ${it.name}. Available ${stock(d.companyId,it.productId)}`);db.stockMovements.push({id:uid(),companyId:d.companyId,productId:it.productId,type:sign,qty:it.qty,unitCost:it.unitPrice,referenceType:'document',referenceId:d.id,note:d.number,date:d.date,createdBy:req.user.id,createdAt:now()})}}
 db.documents.unshift(d);const accName=d.type==='purchase'?'Purchase':'Sales';let acc=db.accounts.find(a=>a.companyId===d.companyId&&a.name===accName);if(acc){acc.balance=money(Number(acc.balance||0)+(d.type==='purchase'?-d.total:d.total));acc.updatedAt=now();db.ledgerEntries.unshift({id:uid(),companyId:d.companyId,accountId:acc.id,partyId:d.partyId||null,documentId:d.id,type:d.type,amount:d.total,debit:d.type==='purchase'?d.total:0,credit:d.type==='purchase'?0:d.total,date:d.date,narration:d.number,createdBy:req.user.id,createdAt:now()})}if(b.mark_paid&&d.partyId&&['invoice','non_gst','purchase'].includes(d.type)){const party=db.parties.find(x=>x.id===d.partyId);if(party){db.payments.unshift({id:uid(),companyId:d.companyId,partyId:d.partyId,type:party.type==='customer'?'receipt':'payment',amount:d.total,date:d.date,mode:d.payment_mode||'Cash',reference:d.number,note:`Auto-settled ${d.number}`,documentId:d.id,createdBy:req.user.id,createdAt:now()});}}audit(req,'create','document',d.id,d.companyId,{type:d.type,number:d.number,total:d.total});return d}
function docWithParty(d){const p=db.parties.find(x=>x.id===d.partyId);return {...clone(d),partyName:p?.name||null,partyGstin:p?.gstin||null}}

function pdfEscape(s){return String(s??'').replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)')}function makePdf(lines){const content=['BT','/F1 11 Tf','45 800 Td',...lines.flatMap((l,i)=>[`${i?0:-0} -16 Td`, `(${pdfEscape(l)}) Tj`]),'ET'].join('\n');const stream=zlib.deflateSync(Buffer.from(content));const objs=[];objs.push('<< /Type /Catalog /Pages 2 0 R >>');objs.push('<< /Type /Pages /Kids [3 0 R] /Count 1 >>');objs.push('<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>');objs.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');objs.push(`<< /Length ${stream.length} /Filter /FlateDecode >>\nstream\n${stream.toString('binary')}\nendstream`);let out='%PDF-1.4\n',offs=[0];objs.forEach((o,i)=>{offs[i+1]=Buffer.byteLength(out,'binary');out+=`${i+1} 0 obj\n${o}\nendobj\n`});const start=Buffer.byteLength(out,'binary');out+=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n`;for(let i=1;i<=objs.length;i++)out+=`${String(offs[i]).padStart(10,'0')} 00000 n \n`;out+=`trailer\n<< /Size ${objs.length+1} /Root 1 0 R >>\nstartxref\n${start}\n%%EOF`;return Buffer.from(out,'binary')}

async function route(req,res){const parsed=url.parse(req.url,true);const pathname=parsed.pathname;const method=req.method;
 if(pathname==='/api/health'&&method==='GET')return json(res,200,{ok:true,version:'3.0.0'});
 if(pathname==='/api/auth/login'&&method==='POST'){const b=await body(req);const u=db.users.find(x=>x.email===safe(b.email,150).toLowerCase());if(!u||!verifyPassword(b.password,u.passwordHash))return json(res,401,{error:'Invalid email or password'});return json(res,200,{token:signToken(u.id,Boolean(b.remember)),user:userPublic(u)})}
 if(method==='GET' && !pathname.startsWith('/api/')){
  const rel=pathname==='/'?'index.html':pathname.replace(/^\//,'');
  const publicDir=path.resolve(__dirname,'public');
  const file=path.resolve(publicDir,rel);
  if(file!==publicDir && !file.startsWith(publicDir+path.sep)) return text(res,403,'Forbidden');
  if(fs.existsSync(file)&&fs.statSync(file).isFile()){
   const ext=path.extname(file);
   const ct={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.ico':'image/x-icon'}[ext]||'application/octet-stream';
   const data=fs.readFileSync(file);
   res.writeHead(200,{'Content-Type':ct,'Content-Length':data.length,'Cache-Control':'no-store'});
   return res.end(data);
  }
  return text(res,404,'Not found');
 }
 const user=auth(req,res);if(!user)return;
 if(pathname==='/api/bootstrap'&&method==='GET')return json(res,200,{user:userPublic(user),siteAdmin:!!req.__siteAdmin,companies:clone(db.companies),settings:clone(db.settings),activeCompanyId:db.companies[0]?.id});
 if(pathname==='/api/companies'&&method==='GET')return json(res,200,{companies:clone(db.companies)});
 if(pathname==='/api/site-sync/products'&&method==='POST'){await syncWebsiteProducts();return json(res,200,{ok:true})}
 if(pathname==='/api/site-sync/enquiry'&&method==='POST'){const b=await body(req);const party=await syncEnquiryToParty(b);return json(res,200,{ok:true,party:party?clone(party):null})}
 const cm=pathname.match(/^\/api\/companies\/([^/]+)$/);if(cm&&method==='PATCH'){if(!user.isAdmin)return json(res,403,{error:'Administrator access required'});const b=await body(req);const c=findCompany(cm[1]);if(!c)return json(res,404,{error:'Company not found'});const f=['name','code','description','address','gstin','pan','state','stateCode','state_code','pin','phone','email','bank_name','bankName','bank_branch','bankBranch','account_number','accountNumber','ifsc','account_type','accountType','logo','invoice_prefix','invoicePrefix','quotation_prefix','quotationPrefix','proforma_prefix','proformaPrefix','purchase_prefix','purchasePrefix','challan_prefix','challanPrefix'];for(const k of f){if(bHas(b,k)){const v=b[k];const target={state_code:'stateCode',bank_name:'bankName',bank_branch:'bankBranch',account_number:'accountNumber',account_type:'accountType',invoice_prefix:'invoicePrefix',quotation_prefix:'quotationPrefix',proforma_prefix:'proformaPrefix',purchase_prefix:'purchasePrefix',challan_prefix:'challanPrefix'}[k]||k;c[target]=safe(v,350)}}if(b.terms!==undefined)c.terms=Array.isArray(b.terms)?b.terms:[];c.updatedAt=now();audit(req,'update','company',c.id,c.id,b);await save(db);return json(res,200,{company:clone(c)})}
 if(pathname==='/api/products'&&method==='GET'){return json(res,200,{products:products(parsed.query.companyId)})}
 if(pathname==='/api/products'&&method==='POST'){if(!perm(user,'manageProducts'))return json(res,403,{error:'Permission denied'});const b=await body(req);const p={id:uid(),companyId:safe(b.companyId),sku:safe(b.sku,80),name:safe(b.name,180),category:safe(b.category,120),hsn:safe(b.hsn,40),unit:safe(b.unit,30)||'pcs',gstRate:Number(b.gst_rate)||0,purchasePrice:Number(b.purchase_price)||0,salePrice:Number(b.sale_price)||0,minStock:Number(b.min_stock)||0,openingQty:Number(b.opening_qty)||0,openingValue:Number(b.opening_value)||0,active:true,createdAt:now(),updatedAt:now()};if(!p.name)return json(res,400,{error:'Product name is required'});db.products.push(p);audit(req,'create','product',p.id,p.companyId,b);await save(db);await syncERPProductToWebsite(p);return json(res,201,{product:products(p.companyId).find(x=>x.id===p.id)})}
 const pm=pathname.match(/^\/api\/products\/([^/]+)$/);if(pm&&method==='PATCH'){if(!perm(user,'manageProducts'))return json(res,403,{error:'Permission denied'});const p=findProduct(pm[1]);if(!p)return json(res,404,{error:'Product not found'});const b=await body(req);for(const k of ['sku','name','category','hsn','unit'])if(b[k]!==undefined)p[k]=safe(b[k],180);for(const [a,k] of [['gst_rate','gstRate'],['purchase_price','purchasePrice'],['sale_price','salePrice'],['min_stock','minStock']])if(b[a]!==undefined)p[k]=Number(b[a])||0;p.updatedAt=now();audit(req,'update','product',p.id,p.companyId,b);await save(db);await syncERPProductToWebsite(p);return json(res,200,{product:products(p.companyId).find(x=>x.id===p.id)})}
 if(pm&&method==='DELETE'){if(!user.isAdmin)return json(res,403,{error:'Administrator access required'});const p=findProduct(pm[1]);if(!p)return json(res,404,{error:'Product not found'});p.active=false;p.updatedAt=now();audit(req,'archive','product',p.id,p.companyId,{});await save(db);await syncERPProductToWebsite(p);return json(res,200,{ok:true})}
 if(pathname==='/api/stock'&&method==='POST'){if(!perm(user,'manageProducts'))return json(res,403,{error:'Permission denied'});const b=await body(req),p=findProduct(b.productId),qty=Math.abs(Number(b.qty)||0);if(!p||!qty)return json(res,400,{error:'Product and quantity are required'});if(b.type==='out'&&stock(b.companyId,p.id)<qty)return json(res,400,{error:`Insufficient stock. Available: ${stock(b.companyId,p.id)}`});db.stockMovements.push({id:uid(),companyId:b.companyId,productId:p.id,type:b.type==='out'?'out':'in',qty,unitCost:Number(b.unit_cost)||p.purchasePrice||0,referenceType:'manual',referenceId:null,note:safe(b.note,250),date:safe(b.date,20)||now().slice(0,10),createdBy:user.id,createdAt:now()});audit(req,'create','stock_movement',p.id,b.companyId,b);await save(db);return json(res,200,{ok:true,stock:stock(b.companyId,p.id)})}
 if(pathname==='/api/parties'&&method==='GET')return json(res,200,{parties:partyBalances(parsed.query.companyId)});
 if(pathname==='/api/parties'&&method==='POST'){const b=await body(req);if(!['customer','supplier'].includes(b.type))return json(res,400,{error:'Invalid party type'});const p={id:uid(),companyId:safe(b.companyId),type:b.type,name:safe(b.name,180),phone:safe(b.phone,50),email:safe(b.email,150),address:safe(b.address,400),gstin:safe(b.gstin,30).toUpperCase(),state:safe(b.state,80),stateCode:safe(b.state_code,10),pin:safe(b.pin,20),openingBalance:Number(b.opening_balance)||0,balanceType:b.type==='customer'?'receivable':'payable',notes:safe(b.notes,300),createdAt:now(),updatedAt:now()};db.parties.push(p);audit(req,'create','party',p.id,p.companyId,b);await save(db);return json(res,201,{party:clone(p)})}
 const par=pathname.match(/^\/api\/parties\/([^/]+)$/);if(par&&method==='PATCH'){const p=db.parties.find(x=>x.id===par[1]);if(!p)return json(res,404,{error:'Party not found'});const b=await body(req);for(const [a,k] of [['name','name'],['phone','phone'],['email','email'],['address','address'],['gstin','gstin'],['state','state'],['state_code','stateCode'],['pin','pin'],['notes','notes']])if(b[a]!==undefined)p[k]=safe(b[a],400);if(b.opening_balance!==undefined)p.openingBalance=Number(b.opening_balance)||0;p.updatedAt=now();audit(req,'update','party',p.id,p.companyId,b);await save(db);return json(res,200,{party:clone(p)})}
 if(pathname==='/api/documents'&&method==='GET'){let docs=db.documents.filter(d=>d.companyId===parsed.query.companyId);if(parsed.query.type)docs=docs.filter(d=>d.type===parsed.query.type);return json(res,200,{documents:docs.slice().sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,500).map(docWithParty)})}
 if(pathname==='/api/documents'&&method==='POST'){const b=await body(req);if(b.type==='purchase'&&!perm(user,'recordPurchases'))return json(res,403,{error:'Permission denied'});if(b.type!=='purchase'&&!perm(user,'recordSales'))return json(res,403,{error:'Permission denied'});try{const d=insertDoc(req,b);await save(db);return json(res,201,{document:clone(d)})}catch(e){return json(res,400,{error:e.message})}}
 const dm=pathname.match(/^\/api\/documents\/([^/]+)\/cancel$/);if(dm&&method==='POST'){const d=db.documents.find(x=>x.id===dm[1]);if(!d)return json(res,404,{error:'Document not found'});if(d.status==='cancelled')return json(res,200,{ok:true});d.status='cancelled';d.updatedAt=now();for(const m of db.stockMovements.filter(x=>x.referenceId===d.id))db.stockMovements.push({...m,id:uid(),type:m.type==='in'?'out':'in',referenceType:'document_cancel',note:`Reversal ${d.number}`,createdAt:now()});audit(req,'cancel','document',d.id,d.companyId,{number:d.number});await save(db);return json(res,200,{ok:true})}
 const pdfm=pathname.match(/^\/api\/documents\/([^/]+)\/pdf$/);if(pdfm&&method==='GET'){const d=db.documents.find(x=>x.id===pdfm[1]);if(!d)return text(res,404,'Not found');const c=findCompany(d.companyId);const lines=[c.name,c.address||'',`GSTIN: ${c.gstin||'-'}   PAN: ${c.pan||'-'}`,`Phone: ${c.phone||'-'}  Email: ${c.email||'-'}`,'',String(d.type).replace('_',' ').toUpperCase(),`Number: ${d.number}    Date: ${d.date}`,'',`Party: ${db.parties.find(p=>p.id===d.partyId)?.name||'-'}`,'','Item                         Qty       Rate       Amount'];for(const it of d.items||[])lines.push(`${String(it.name).slice(0,25).padEnd(27)} ${String(it.qty).padStart(5)} ${money(it.unitPrice).toFixed(2).padStart(10)} ${money(it.lineTotal).toFixed(2).padStart(11)}`);lines.push('','Subtotal: INR '+money(d.subtotal).toFixed(2),'CGST: INR '+money(d.cgst).toFixed(2)+'   SGST: INR '+money(d.sgst).toFixed(2)+'   IGST: INR '+money(d.igst).toFixed(2),'TOTAL: INR '+money(d.total).toFixed(2),'','Terms: '+(d.terms||[]).join(' | '));const pdf=makePdf(lines);res.writeHead(200,{'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="${d.number.replace(/[^A-Za-z0-9_-]/g,'_')}.pdf"`,'Content-Length':pdf.length});return res.end(pdf)}
 if(pathname==='/api/payments'&&method==='GET')return json(res,200,{payments:db.payments.filter(x=>x.companyId===parsed.query.companyId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(p=>({...p,partyName:db.parties.find(q=>q.id===p.partyId)?.name||null}))});
 if(pathname==='/api/payments'&&method==='POST'){if(!perm(user,'managePayments'))return json(res,403,{error:'Permission denied'});const b=await body(req),party=db.parties.find(x=>x.id===b.partyId);if(!party)return json(res,404,{error:'Party not found'});const p={id:uid(),companyId:b.companyId,partyId:b.partyId,type:party.type==='customer'?'receipt':'payment',amount:Number(b.amount)||0,date:safe(b.date,20)||now().slice(0,10),mode:safe(b.mode,40),reference:safe(b.reference,100),note:safe(b.note,300),documentId:b.documentId||null,createdBy:user.id,createdAt:now()};db.payments.unshift(p);audit(req,'create','payment',p.id,p.companyId,b);await save(db);return json(res,201,{payment:clone(p)})}
 if(pathname==='/api/expenses'&&method==='GET')return json(res,200,{expenses:db.expenses.filter(x=>x.companyId===parsed.query.companyId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))});
 if(pathname==='/api/expenses'&&method==='POST'){if(!user.isAdmin)return json(res,403,{error:'Administrator access required'});const b=await body(req);const e={id:uid(),companyId:b.companyId,category:safe(b.category,100)||'General',amount:Number(b.amount)||0,date:safe(b.date,20)||now().slice(0,10),mode:safe(b.mode,40),note:safe(b.note,300),createdBy:user.id,createdAt:now()};db.expenses.unshift(e);const a=db.accounts.find(x=>x.companyId===e.companyId&&x.name==='Expenses');if(a)a.balance=money(a.balance+e.amount);audit(req,'create','expense',e.id,e.companyId,b);await save(db);return json(res,201,{expense:clone(e)})}
 if(pathname==='/api/ledger'&&method==='GET'){const cid=parsed.query.companyId;return json(res,200,{accounts:db.accounts.filter(a=>a.companyId===cid),entries:db.ledgerEntries.filter(x=>x.companyId===cid).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,1000).map(e=>({...e,accountName:db.accounts.find(a=>a.id===e.accountId)?.name||'',partyName:db.parties.find(p=>p.id===e.partyId)?.name||null,documentNumber:db.documents.find(d=>d.id===e.documentId)?.number||null}))})}
 if(pathname==='/api/reports/summary'&&method==='GET'){const cid=parsed.query.companyId,month=parsed.query.month||now().slice(0,7),ds=db.documents.filter(d=>d.companyId===cid&&d.status!=='cancelled'&&d.date.startsWith(month)),sales=ds.filter(d=>['invoice','non_gst'].includes(d.type)),purch=ds.filter(d=>d.type==='purchase'),prods=products(cid);const receipts=db.payments.filter(x=>x.companyId===cid&&x.type==='receipt'&&x.date.startsWith(month)).reduce((s,x)=>s+x.amount,0),paid=db.payments.filter(x=>x.companyId===cid&&x.type==='payment'&&x.date.startsWith(month)).reduce((s,x)=>s+x.amount,0),expenses=db.expenses.filter(x=>x.companyId===cid&&x.date.startsWith(month)).reduce((s,x)=>s+x.amount,0);return json(res,200,{salesAmount:money(sales.reduce((s,x)=>s+x.total,0)),sales:{c:sales.length},purchaseAmount:money(purch.reduce((s,x)=>s+x.total,0)),purchases:{c:purch.length},receipts:money(receipts),paid:money(paid),expenses:money(expenses),inventoryValue:money(prods.reduce((s,x)=>s+x.stock_value,0)),productCount:prods.length,lowStock:prods.filter(x=>x.minStock>0&&x.stock<=x.minStock),recentDocs:db.documents.filter(x=>x.companyId===cid).slice(0,8).map(docWithParty)})}
 if(pathname==='/api/users'&&method==='GET'){if(!user.isAdmin)return json(res,403,{error:'Administrator access required'});return json(res,200,{users:db.users.map(userPublic)})}
 if(pathname==='/api/users'&&method==='POST'){if(!user.isAdmin)return json(res,403,{error:'Administrator access required'});const b=await body(req),email=safe(b.email,150).toLowerCase();if(db.users.some(x=>x.email===email))return json(res,409,{error:'Email already exists'});const u={id:uid(),name:safe(b.name,100)||'Staff',email,passwordHash:hashPassword(b.password||''),role:safe(b.role,80)||'Staff',isAdmin:false,permissions:b.permissions||{viewAmounts:false,recordSales:true,recordPurchases:true,manageProducts:true,managePayments:false,manageSettings:false},createdAt:now(),updatedAt:now()};db.users.push(u);await save(db);return json(res,201,{user:userPublic(u)})}
 const um=pathname.match(/^\/api\/users\/([^/]+)$/);if(um&&method==='PATCH'){if(!user.isAdmin)return json(res,403,{error:'Administrator access required'});const u=db.users.find(x=>x.id===um[1]);if(!u)return json(res,404,{error:'User not found'});const b=await body(req);for(const k of ['name','email','role'])if(b[k]!==undefined)u[k]=safe(b[k],150);if(b.permissions)u.permissions=b.permissions;if(b.password)u.passwordHash=hashPassword(b.password);u.updatedAt=now();await save(db);return json(res,200,{user:userPublic(u)})}
 if(pathname==='/api/me/password'&&method==='POST'){const b=await body(req);if(!verifyPassword(b.currentPassword,user.passwordHash))return json(res,400,{error:'Current password is incorrect'});if(String(b.newPassword||'').length<6)return json(res,400,{error:'New password must be at least 6 characters'});user.passwordHash=hashPassword(b.newPassword);user.updatedAt=now();await save(db);return json(res,200,{ok:true})}
 if(pathname==='/api/audit'&&method==='GET'){if(!user.isAdmin)return json(res,403,{error:'Administrator access required'});return json(res,200,{logs:db.auditLogs.map(x=>({...x,userName:db.users.find(u=>u.id===x.userId)?.name||null,companyName:findCompany(x.companyId)?.name||null}))})}
 if(pathname==='/api/backup'&&method==='GET'){if(!user.isAdmin)return json(res,403,{error:'Administrator access required'});return json(res,200,clone(db))}
 if(pathname==='/api/restore'&&method==='POST'){if(!user.isAdmin)return json(res,403,{error:'Administrator access required'});const b=await body(req);if(!b||!b.version||!b.companies)return json(res,400,{error:'Invalid backup'});db=b;await save(db);return json(res,200,{ok:true})}
 if(method==='GET'&&pathname.startsWith('/')){const rel=pathname==='/'?'index.html':pathname.replace(/^\//,'');const file=path.join(__dirname,'public',rel);if(!file.startsWith(path.join(__dirname,'public')))return text(res,403,'Forbidden');if(fs.existsSync(file)&&fs.statSync(file).isFile()){const ext=path.extname(file);const ct={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg'}[ext]||'application/octet-stream';const data=fs.readFileSync(file);res.writeHead(200,{'Content-Type':ct,'Cache-Control':'no-store'});return res.end(data)}return text(res,404,'Not found')}
 return json(res,404,{error:'Not found'});
}
function bHas(o,k){return Object.prototype.hasOwnProperty.call(o,k)}function perm(u,k){return u.isAdmin||u.permissions?.[k]}
async function startStandalone(){await initializeERP();const server=http.createServer((req,res)=>{route(req,res).catch(e=>{console.error(e);json(res,500,{error:'Server error'})})});server.listen(PORT,()=>console.log(`Swaraj ERP running at http://localhost:${PORT}`));}
module.exports={route,initializeERP,save,getDbState:()=>db,syncWebsiteProducts,syncERPProductToWebsite,syncEnquiryToParty};
if(require.main===module)startStandalone().catch(e=>{console.error(e);process.exit(1)});
